apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: backend-staging-cert
spec:
  secretName: backend-staging-cert
  dnsNames:
  - backend.coinflip.click
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - backend.coinflip.click
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
