apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: frontend-cert-prod
spec:
  secretName: frontend-cert-prod
  dnsNames:
  - coinflip.click
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - coinflip.click
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
