apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: frontend-cert-staging
spec:
  secretName: frontend-cert-staging
  dnsNames:
  - coinflip.click
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - coinflip.click
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
