apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: test-ingress-cert
spec:
  secretName: test-ingress-cert
  dnsNames:
  - test.coinflip.click
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - test.coinflip.click
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
