{{- if .Values.ingress.enabled -}}
{{- $fullName := include "randomdistrib-build.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "randomdistrib-build.name" . }}
    helm.sh/chart: {{ include "randomdistrib-build.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: "coinflip.click"
      http:
        paths:
          - path: /*
            backend:
              serviceName: randomdistrib-frontend
              servicePort: http
    - host: "backend.coinflip.click"
      http:
        paths:
          - path: /*
            backend:
              serviceName: randomdistrib-backend
              servicePort: http
{{- end }}
