apiVersion: v1
kind: Service
metadata:
  name: randomdistrib-backend
  labels:
    app.kubernetes.io/name: {{ include "randomdistrib-build.name" . }}
    helm.sh/chart: {{ include "randomdistrib-build.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: randomdistrib-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
